/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inst.interfaces;

import inst.objects.Space;
import java.awt.Font;
import java.util.Arrays;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;



/**
 *
 * @author wilknis
 */
public class MainInterface extends javax.swing.JFrame {
    //COMMON
    boolean getFont = false;
    String fontName;
    
    //FOR GENERAL TAB
    //It's to use list, that os linked to listSpace
    DefaultListModel listSpaceSupport = new DefaultListModel();
    int select;
    
    //Objects
    Space space[] = new Space[50];   //Object vector to space object
    
    
    /**
     * Creates new form MainInterface
     */
    public MainInterface() {
        initComponents();
        
        paneSpaces.setVisible(true);
        boldPlainName(lblSpace, true);
        paneTugIlu.setVisible(false);
    }
    
    //### COMMON ###
    
    //Function to change a label to bold with a easy way.
    private void boldPlainName(JLabel lbl, boolean choise){
        Font font = lbl.getFont();
        Font fontModify;
        
        //Get the name once the first time.
        if(getFont == false){
            fontName = font.getFontName();
            getFont = true;
        }
        
        //Change only the style
        if(choise == true){
            fontModify = new Font(fontName,Font.BOLD, font.getSize());
        }
        else{
            fontModify = new Font(fontName,Font.PLAIN, font.getSize());
        }
        
        lbl.setFont(fontModify);
    }
    
    
    //### SPACE IN GENERAL TAB ###
    private void showSpaceInGeneral(){
        listSpaceSupport.removeAllElements();
        for (int i=0;i<space.length;i++) {
            if(space[i]!=null)
                listSpaceSupport.addElement(space[i].getSpace());
        }
    }
    
    private void getInputSpaceData(int i){
        String spInput = txtSpace.getText();
        String tyInput = cBType.getSelectedItem().toString();
        float areaInput = Float.parseFloat(spnArea.getValue().toString());
        float perimeterInput = Float.parseFloat(spnPerimeter.getValue().toString());

        space[i] = new Space(spInput, tyInput, areaInput, perimeterInput);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabSections = new javax.swing.JTabbedPane();
        paneGeneral = new javax.swing.JPanel();
        splitPane = new javax.swing.JSplitPane();
        sideBar = new javax.swing.JPanel();
        lblSpace = new javax.swing.JLabel();
        lblTugIlu = new javax.swing.JLabel();
        mainRight = new javax.swing.JPanel();
        paneTugIlu = new javax.swing.JPanel();
        paneSpaces = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtSpace = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cBType = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        spnArea = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        spnPerimeter = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        listSpace = new javax.swing.JList<>();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnChange = new javax.swing.JButton();
        btnOrder = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        upperMenu = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        testFileMenu = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        testEditMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sideBar.setPreferredSize(new java.awt.Dimension(200, 500));

        lblSpace.setText("Espaços");
        lblSpace.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSpace.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSpaceMouseClicked(evt);
            }
        });

        lblTugIlu.setText("TUG e Iluminação");
        lblTugIlu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblTugIlu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTugIluMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout sideBarLayout = new javax.swing.GroupLayout(sideBar);
        sideBar.setLayout(sideBarLayout);
        sideBarLayout.setHorizontalGroup(
            sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSpace)
                    .addComponent(lblTugIlu))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sideBarLayout.setVerticalGroup(
            sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblSpace)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTugIlu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        splitPane.setLeftComponent(sideBar);

        mainRight.setBackground(new java.awt.Color(255, 255, 255));
        mainRight.setLayout(new javax.swing.OverlayLayout(mainRight));

        paneTugIlu.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout paneTugIluLayout = new javax.swing.GroupLayout(paneTugIlu);
        paneTugIlu.setLayout(paneTugIluLayout);
        paneTugIluLayout.setHorizontalGroup(
            paneTugIluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        paneTugIluLayout.setVerticalGroup(
            paneTugIluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        mainRight.add(paneTugIlu);

        paneSpaces.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setText("Espaço:");

        jLabel4.setText("Tipo:");

        cBType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Banheiro", "Áreas molhadas", "Varanda", "Salas/Dormitórios", "<=2,25m²", "2,25m²<x<6m²", ">6m²", "Externo", "Garagem" }));

        jLabel5.setText("Área:");

        jLabel6.setText("Perímetro:");

        listSpace.setModel(listSpaceSupport);
        listSpace.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listSpaceMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listSpace);

        btnAdd.setText("Adicionar");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnDelete.setText("Apagar");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnChange.setText("Alterar");
        btnChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeActionPerformed(evt);
            }
        });

        btnOrder.setText("Ordenar");
        btnOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneSpacesLayout = new javax.swing.GroupLayout(paneSpaces);
        paneSpaces.setLayout(paneSpacesLayout);
        paneSpacesLayout.setHorizontalGroup(
            paneSpacesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneSpacesLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(paneSpacesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneSpacesLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(paneSpacesLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(21, 21, 21)))
                .addGroup(paneSpacesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneSpacesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(paneSpacesLayout.createSequentialGroup()
                            .addComponent(btnAdd)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnOrder)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnChange)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnDelete)))
                    .addGroup(paneSpacesLayout.createSequentialGroup()
                        .addGroup(paneSpacesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSpace)
                            .addComponent(cBType, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(paneSpacesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(paneSpacesLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(spnArea, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(paneSpacesLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spnPerimeter, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        paneSpacesLayout.setVerticalGroup(
            paneSpacesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneSpacesLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(paneSpacesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtSpace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(spnArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paneSpacesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(spnPerimeter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cBType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(paneSpacesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnDelete)
                    .addComponent(btnChange)
                    .addComponent(btnOrder))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainRight.add(paneSpaces);

        splitPane.setRightComponent(mainRight);

        javax.swing.GroupLayout paneGeneralLayout = new javax.swing.GroupLayout(paneGeneral);
        paneGeneral.setLayout(paneGeneralLayout);
        paneGeneralLayout.setHorizontalGroup(
            paneGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane)
        );
        paneGeneralLayout.setVerticalGroup(
            paneGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane)
        );

        tabSections.addTab("Geral", paneGeneral);

        jLabel2.setText("tab2");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(267, 267, 267)
                .addComponent(jLabel2)
                .addContainerGap(577, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(jLabel2)
                .addContainerGap(344, Short.MAX_VALUE))
        );

        tabSections.addTab("Circuitos", jPanel2);

        fileMenu.setText("Arquivo");

        testFileMenu.setText("Test");
        testFileMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testFileMenuActionPerformed(evt);
            }
        });
        fileMenu.add(testFileMenu);

        upperMenu.add(fileMenu);

        editMenu.setText("Editar");

        testEditMenu.setText("testEditMenu");
        editMenu.add(testEditMenu);

        upperMenu.add(editMenu);

        setJMenuBar(upperMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabSections)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabSections)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void testFileMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testFileMenuActionPerformed
       
    }//GEN-LAST:event_testFileMenuActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed

        int i = 0;
        int i1 = 0;
        while(i1 == 0){
            if(space[i]==null){
                getInputSpaceData(i);
                i1 = 1;
            }
            i++;
        }
        
        //Add the objects space to the list.
        showSpaceInGeneral();
        
        txtSpace.setText("");
        cBType.setSelectedItem("Item 1");
        spnArea.setValue(0);
        spnPerimeter.setValue(0);
    }//GEN-LAST:event_btnAddActionPerformed

    private void listSpaceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listSpaceMouseClicked
        select = listSpace.getSelectedIndex();
        
        txtSpace.setText(space[select].getSpace());
        cBType.setSelectedItem(space[select].getType());
        spnArea.setValue(space[select].getArea());
        spnPerimeter.setValue(space[select].getPerimeter());
    }//GEN-LAST:event_listSpaceMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        space[select] = null;
        showSpaceInGeneral();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeActionPerformed
        getInputSpaceData(select);
        showSpaceInGeneral();
    }//GEN-LAST:event_btnChangeActionPerformed

    private void btnOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderActionPerformed
        
        //To sort string
        Arrays.sort(space, (a, b) -> {
            if (a == null && b == null) {
                return 0;
            } else if (a == null) {
                return 1;
            } else if (b == null) {
                return -1;
            } else {
                String pa = a.getSpace();
                String pb = b.getSpace();

                return pa.compareTo(pb) < 0 ? -1 : pa.compareTo(pb) > 0 ? 1: 0;
            }
        });
        
        showSpaceInGeneral();
        
    }//GEN-LAST:event_btnOrderActionPerformed

    private void lblSpaceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSpaceMouseClicked
        paneSpaces.setVisible(true);
        paneTugIlu.setVisible(false);
        
        boldPlainName(lblSpace, true);
        boldPlainName(lblTugIlu, false);
    }//GEN-LAST:event_lblSpaceMouseClicked

    private void lblTugIluMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTugIluMouseClicked
        paneSpaces.setVisible(false);
        paneTugIlu.setVisible(true);
        
        boldPlainName(lblSpace, false);
        boldPlainName(lblTugIlu, true);
    }//GEN-LAST:event_lblTugIluMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnChange;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnOrder;
    private javax.swing.JComboBox<String> cBType;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSpace;
    private javax.swing.JLabel lblTugIlu;
    private javax.swing.JList<String> listSpace;
    private javax.swing.JPanel mainRight;
    private javax.swing.JPanel paneGeneral;
    private javax.swing.JPanel paneSpaces;
    private javax.swing.JPanel paneTugIlu;
    private javax.swing.JPanel sideBar;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JSpinner spnArea;
    private javax.swing.JSpinner spnPerimeter;
    private javax.swing.JTabbedPane tabSections;
    private javax.swing.JMenuItem testEditMenu;
    private javax.swing.JMenuItem testFileMenu;
    private javax.swing.JTextField txtSpace;
    private javax.swing.JMenuBar upperMenu;
    // End of variables declaration//GEN-END:variables
}
